### ISSUE TITLE
Passphrase step

### ISSUE THREAD

**Issue by enricopesce** [Burnett01/rsync-deployments#10]
Hi, is there an example of private key authentication including a passphrase? 

 I'm blocked in the action with 

`entering the passphrase for (stdin):  `

 I can't find an input option such as remote_passphrase for passing to the stdin the password  

Thank you!

**Comment by Burnett01** [comment]
Hey @enricopesce ,

this could work when providing an ssh-agent with the key prior to running the rsync command.
A couple of other options might help too:  https://github.com/Burnett01/rsync-deployments/issues/9

**Comment by Burnett01** [comment]
I am closing this until further steps are provided whether this is something to support in this action.

**Comment by Burnett01** [comment]
@enricopesce  Good news, you can now use passphrase protected key with version 5.0

https://github.com/Burnett01/rsync-deployments/releases/tag/5.0
