### ISSUE TITLE
How to push the entire repo to the remote folder?

### ISSUE THREAD

**Issue by praveentcom** [Burnett01/rsync-deployments#11]
I tried without using the `path` variable, and also "", but it's not copying everything.

**Comment by Burnett01** [comment]
Hey, the default path is set to ``GITHUB_WORKSPACE`` which is the the most recent path after running the ``actions/checkout`` action.
Leaving out the ``path`` attribute will evalute the path to ``GITHUB_WORKSPACE/`` which results in deploying the entire repo to a remote folder.
I was not able to re-produce your issue during my tests earlier today.

Please let me know if I can assist you any further. Greetings, Steve

**Comment by praveentcom** [comment]
I didn't add the check out step to the build. I am now able to complete the intended action.
