### ISSUE TITLE
Error when sync

### ISSUE THREAD

**Issue by pdiaz85** [Burnett01/rsync-deployments#17]
Hi im been using this action for a while, but now i'm having this issue with  burnett01/rsync-deployments@4.1.
When trying to sync files i got this error
`rsync: mkdir "/***/2087:***" failed: No such file or directory (2)`
```
rsync error: error in file IO (code 11) at main.c(664) [Receiver=3.1.3]
rsync: [sender] write error: Broken pipe (32)

```
I don't  know why rsync is adding /***/2087: to the destination path.
Please advice
Thanks

**Comment by Burnett01** [comment]
> Nevermind my bad, i was using the IP on remote_host instead of hostname.
> 
> Thank you , nice Action indeed.

Hey thank you for reaching out 🙋‍♂️ You can use the ip directly in addition to using the hostname. Am not quite sure as to why the connection did not succeed on your first attempt, but I guess it might be related to a wrong/missing remote_path.  
Maybe your server doesn't allow for connecting via IP either (Firewall), hence using the hostname was successful. Nonetheless I'm glad you fixed the issue and thank you for letting us know. 

Greetings Steve
