### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by adamafsar** [Burnett01/rsync-deployments#25]
Hi, 

I have been getting the following error

rsync: mkdir "/var/www/html/beta_ia_site_uk" failed: Permission denied (13)

Been trying to trouble shoot but not sure what it could be

<img width="1496" alt="Screenshot 2022-03-26 at 11 15 57 am" src="https://user-images.githubusercontent.com/70033913/160236966-9f5fd4b2-8360-420c-afea-bd1a6e5ad25a.png">

**Comment by Burnett01** [comment]
Hello @adamafsar do you have the correct permissions for that user on the server? To me it looks like you are using an ssh user that is not allowed to perform fs operations.
