### ISSUE TITLE
rsync: mkdir "/var/www/html" failed

### ISSUE THREAD

**Issue by lixd** [Burnett01/rsync-deployments#29]
logs
```console
Identity added: (stdin) ((stdin))
Warning: Permanently added '***' (ECDSA) to the list of known hosts.
sending incremental file list
rsync: mkdir "/var/www/html" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]
```

rsync cannot create dir recursion. like mkdir -p.
so, maybe we can create dir before rsync.

**Comment by Burnett01** [comment]
Thank you very much for your report and the proposal. I will have to check if rsync can handle non-existing nested dirs or if infact mkdir should be used.

Greetings Steve
