### ISSUE TITLE
Suggested additions to readme

### ISSUE THREAD

**Issue by kgilmer** [Burnett01/rsync-deployments#31]
Thanks for your work, I have a few minor suggestions that may help others when evaluating your action:

* Document that `path` is relative to the github workspace.  This means that only sub-paths of the workspace may be uploaded.
* Document that the action can only run on `amd64` hosts.  arm build hosts cannot use this action.

**Comment by Burnett01** [comment]
Hey @kgilmer Thank you very much. I will adjust the readme. Greetings Steve

**Comment by Burnett01** [comment]
Done in [d2a4efa](https://github.com/Burnett01/rsync-deployments/commit/d2a4efa87c52ef2e77cc5727734cc89c313be3f9).
Thank you again.
