### ISSUE TITLE
Job doesn't fail if SSH Key Passphrase is wrong

### ISSUE THREAD

**Issue by olach** [Burnett01/rsync-deployments#37]
Recently when I configured a new deploy workflow, I accidentally entered a wrong SSH Key Passphrase.

When the rsync deployment job was running, it was running and running forever. No files was uploaded. No errors was shown. I couldn't figure out why it was not working. I had to terminate the job manually, and the logs showed no error.

After a while I realized that I had entered a wrong Passphrase. After correcting this, the next deployment was working correctly.

So, it seems that if the Passphrase is wrong, the action does not abort or shows any error messages. It just keeps running until I manually abort.

I don't know if this is possible for you to handle in your action or not. Maybe it is a limitation in Rsync. But I just wanted to let you know.

Thanks for a great action!

**Comment by Burnett01** [comment]
Hello @olach  thank you very much for your report. I will make sure to investigate this over the weekend.
Greetings, Steve
