### ISSUE TITLE
Fails inside containers due to reliance on $GITHUB_WORKSPACE

### ISSUE THREAD

**Issue by edmundsj** [Burnett01/rsync-deployments#41]
This action does not work inside containers, as paths can only be relative to `$GITHUB_WORKSPACE`. Current workaround is to copy files that need to be `rsync`-ed from the container directory to `$GITHUB_WORKSPACE`. Suggest allowing absolute paths to be used by prefixing the `path` variable with a forward slash `/`.

**Comment by Burnett01** [comment]
Thank you for this report @edmundsj 
The intended default of this action is to follow relative paths to the Github workspace.
I will check if absolute paths can be supported.

Greetings Steve
