### ISSUE TITLE
Passing an empty Github Action variable to `remote_path` circumvents validation and targets the root `/` directory

### ISSUE THREAD

**Issue by maximilliangeorge** [Burnett01/rsync-deployments#44]
As the title says, I accidentally passed an empty variable to `remote_path` (I wrote `${{ env.REMOTE_PATH }}` instead of `${{ vars.REMOTE_PATH }}`). I was expecting this action to throw an error if I had mistyped, but the action actually ran and – you know the rest. I basically nuked the root directory of the remote server, since I also passed the `--delete` flag.

A more fool proof validation of the required input variables would be appreciated.

**Comment by Burnett01** [comment]
Hello thank you for your message.
That is unfortunate that you accidentally nuked your root dir.
In the next version it will no longer be possible to supply an empty string to the remote_path key.

Greetings

Steve

**Comment by Burnett01** [comment]
The fix has been released as a new major (6.0.0) alongside other small improvements to the readme.

Thank you very much.  Changelog https://github.com/Burnett01/rsync-deployments/releases/tag/6.0.0

Greetings

Steven
