### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by RizwanAliHabibi** [Burnett01/rsync-deployments#52]
It is syncying all the files including non incremental files even if I used rsync with -avzr option !

**Comment by Burnett01** [comment]
Hi @RizwanAliHabibi 

have you tried using the filter switches?

`--exclude="" --include="" --filter=""`

**Comment by RizwanAliHabibi** [comment]
Sir, yeah I used --exclude=""

**Comment by apopqo** [comment]
Hi @RizwanAliHabibi,

Have your tried `rsync`'s `-c, --checksum` option? It should "skip based on checksum, not mod-time & size".
