### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by L-Super** [Burnett01/rsync-deployments#53]
![image](https://github.com/Burnett01/rsync-deployments/assets/40905056/755e8252-925d-41bd-bdb4-a45407fb4e85)

I tried pushing to the server locally, and it worked, but failed on Actions.

**Comment by 0xdv** [comment]
Hi! Check you added your public key to `.ssh/authorized_keys` file
Just resolved it for myself, seems to be common issue here

**Comment by Burnett01** [comment]
Hi @L-Super 

Looks like your key is not valid or not yet added to the authorized_keys on your host.
Please follow the instructions @0xdv gave above and report back :)

Thanks

**Comment by L-Super** [comment]
Isn't the public key automatically generated and added?

 `secrets.DEPLOY_KEY` is the public key, not the password, right?

**Comment by Burnett01** [comment]
No, secrets.DEPLOY_KEY is your private key needed for Github Actions Runners to connect to your host.

**Comment by L-Super** [comment]
> @L-Super
> 
> 1. generate new key by `ssh-keygen`, now you have `id_rsa` (private) and `id_rsa.pub` files (public)
> 2. add content of `id_rsa.pub` to `.ssh/authorized_keys` on your target server
> 3. `id_rsa` goes to `secrets.DEPLOY_KEY`
> 
> * if you typed a passphrase when created the key on step 1, place it to `secrets.DEPLOY_KEY_PASS`

Thank you very much!

**Comment by L-Super** [comment]
I misunderstood the `DEPLOY_KEY`.
My Solution:
1. Go to the cloud server console ( like Ali Cloud console) , create the key, you will get the  `key.pem` file, the content of which is `DEPLOY_KEY`
2. Add to Actions secrets and variables

**Comment by rafalolszewski94** [comment]
> @L-Super
> 
> 1. generate new key by `ssh-keygen`, now you have `id_rsa` (private) and `id_rsa.pub` files (public)
> 2. add content of `id_rsa.pub` to `.ssh/authorized_keys` on your target server
> 3. `id_rsa` goes to `secrets.DEPLOY_KEY`
> 
> * if you typed a passphrase when created the key on step 1, place it to `secrets.DEPLOY_KEY_PASS`

I've tried this with several keys, didn't help and still action throws permission denied.

**Comment by L-Super** [comment]
> I misunderstood the `DEPLOY_KEY`.
> My Solution:
> 1. Go to the cloud server console ( like Ali Cloud console) , create the key, you will get the  `key.pem` file, the content of which is `DEPLOY_KEY`
> 2. Add to Actions secrets and variables

try it @rafalolszewski94

**Comment by rafalolszewski94** [comment]
Do you add it to **Secrets and Variables -> Actions** or to **Deploy keys**?

**Comment by L-Super** [comment]
> Do you add it to **Secrets and Variables -> Actions** or to **Deploy keys**?

`your_key.pem` file is the `DEPLOY_KEY`

**Comment by rafalolszewski94** [comment]
Yes, that I understand, but where do you put `DEPLOY_KEY` to which section in repo settings?

**Comment by L-Super** [comment]
> Yes, that I understand, but where do you put `DEPLOY_KEY` to which section in repo settings?

 **Secrets and Variables -> Actions**
